[package]
name = "kirchoff_law"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
queues = "1.1.0"
regex = "1.9.1"
